# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MobileNOCTask' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileNOCTask
  pod 'Alamofire'

  target 'MobileNOCTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileNOCTaskUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
